name: flutter_social_media_app_ally
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  firebase_ui_auth: ^1.1.17
  firebase_auth: ^4.3.0
  firebase_ui_localizations: ^1.2.0
  firebase_ui_oauth_google: ^1.0.24

  # Core
  flutter_riverpod: ^2.3.2
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.20

  # Utility
  animated_text_kit: ^4.2.2
  get_it: ^7.2.0
  auto_route: ^6.0.3
  bot_toast: ^4.0.3
  flutter_svg: ^1.1.6
  animate_do: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^6.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
