// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtNQyWqQkNyf_-h_WDjecyb5NUaU7i7rk',
    appId: '1:828226341895:web:68c5142937897e09b22ea2',
    messagingSenderId: '828226341895',
    projectId: 'flutter-social-media-app-ally',
    authDomain: 'flutter-social-media-app-ally.firebaseapp.com',
    storageBucket: 'flutter-social-media-app-ally.appspot.com',
    measurementId: 'G-6X14QS6VEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-LXECsdNSncXb_IQV_wpZx_PznTJXejs',
    appId: '1:828226341895:android:dafca5e08050ae41b22ea2',
    messagingSenderId: '828226341895',
    projectId: 'flutter-social-media-app-ally',
    storageBucket: 'flutter-social-media-app-ally.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsnxpxTHkNl_uTt4wzD-uVke5FXzP49YY',
    appId: '1:828226341895:ios:92f06501ade2ae32b22ea2',
    messagingSenderId: '828226341895',
    projectId: 'flutter-social-media-app-ally',
    storageBucket: 'flutter-social-media-app-ally.appspot.com',
    iosClientId: '828226341895-65ps5sjqqg86u4vurdnqn47d6h11qd6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSocialMediaAppAlly',
  );
}
